db.ventas2.insertMany ([
    { _id : 1, item : "TP-LINK TL-WR850N",
    class : "informática y wifi", 
    quantity : 15, 
    date : new Date("2020-02-28"),
    price : 18.00,
    premiun:true,
    delivery:"SEUR",
    client : "Octan Corporation", seller : "Félix Matuerzo"},
    { _id : 2, item : "BEHRINGER PK110", 
    class : "sonido",
    quantity : 2, 
    date :  new Date("2019-05-15"),
    price : 50.00,
    premiun:true,
    delivery:"UPS",
    client : "Boah Music", seller : "Rodrigo Duarte"},
    {_id : 3, item : "SHURE MOTIV MV7-K",
    class : "sonido", 
    quantity : 3, 
    date :  new Date("2020-09-21"),
    price : 275.00,
    premiun:true,
    delivery:"SEUR",
    client : "Vice Productions", seller : "Fernando Vazquez"},
    {_id : 4, item : "Transceptor Móvil DYNASCAN 10 M",
    class : "emisoras", 
    quantity : 4, 
    date :  new Date("2020-06-05"),
    price : 170.00,
    premiun:true,
    delivery:"DHL",
    client : "Blackwater", seller : "María Lopez"},
    {_id : 5, item : "GRAUTA ANV-35",
    class : "telefonía", 
    quantity : 40, 
    date :  new Date("2020-03-19"),
    price : 63.98 ,
    premiun:true,
    delivery: "SEUR",
    client : "Telecom", seller : "Antonio Molina"},
    {_id : 6, item : "Cámara Domo Dahua HAC-HDW2802T-Z-A",
    class : "seguridad y porteros", 
    quantity : 12, 
    date : new Date("2020-11-09"),
    price : 126.24 ,
    premiun: true,
    delivery:"SEUR",
    client : "Blackwater", seller : "Marcos Guerrero"},
    {_id : 7, item : "Antena Parabolica Offset 180 CM",
    class : "recepción TV", 
    quantity : 2, 
    date :  new Date("2020-12-11"),
    price : 786.38 ,
    premiun:true,
    delivery:"UPS",
    client : "Telecom", seller : "Marta Galisteo"},
    {_id : 8, item : "TP-LINK TL-WA850RE",
    class : "informática y wifi", 
    quantity : 20, 
    date :  new Date("2019-08-08"),
    price : 21.53,
    premiun:true,
    delivery:"DHL",
    client : "Octan Coporation", seller : "Sonia Sanchez"}

])
